Repository se761group2/industry-4, pull requests merged in 2020-09, with the labels that each got.

#29 Fix end of line CR error
  app/.eslintrc
Labels: bug

#28 Add run instructions to ReadMe
  README.md
Labels: documentation

#36 Sensor graph recharts
  app/src/components/LineGraph.tsx
  app/src/pages/Page.tsx
  package-lock.json
  package.json
Labels: task

#37 Margeobur/apollo data types
  api/functions/src/generated/graphql.ts
  api/functions/src/graphql/MachineStore.ts
  api/functions/src/graphql/resolvers.ts
  api/functions/src/graphql/resolvers/date.ts
  api/functions/src/graphql/resolvers/machine.ts
  api/functions/src/graphql/resolvers/mutation.ts
  api/functions/src/graphql/resolvers/query.ts
  api/functions/src/graphql/resolvers/sensor.ts
  api/functions/src/graphql/schema.graphql
  app/src/common/graphql/queries/machines.ts
  app/src/common/graphql/queries/sensors.ts
  app/src/common/graphql/queries/users.ts
Labels: user story

#39 Move styles to Tailwind
  app/src/components/ExploreContainer.css
  app/src/components/ExploreContainer.tsx
  app/src/components/HealthContainer.css
  app/src/components/HealthContainer.tsx
  app/src/components/LineGraph.tsx
  app/src/pages/Page.css
  app/src/pages/Page.tsx
  app/src/theme/main.css
  app/tailwind.js
Labels: task

#44 Make navbar a component
  app/src/components/Heading.tsx
  app/src/pages/Page.tsx
Labels: task

#50 Sensors page
  app/src/App.tsx
  app/src/common/graphql/queries/machines.ts
  app/src/common/graphql/queries/sensors.ts
  app/src/components/ErrorMessage.tsx
  app/src/components/Heading.tsx
  app/src/components/HealthContainer.tsx
  app/src/pages/Sensor.tsx
  app/src/pages/Sensors.tsx
  app/src/theme/main.css
  app/src/types/getMachineById.ts
  app/src/types/getSensorById.ts
  app/tailwind.js
  package-lock.json
Labels: user story
